version: '3.8'

services:
  api-db:
    image: postgres:14-alpine
    env_file:
      - ./.api_db.env

  rabbitmq:
    image: rabbitmq:alpine
    env_file:
      - ./.rabbitmq.env

  redis:
    image: redis:alpine
    env_file:
      - ./.redis.env

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.tests
    command: pytest
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - api-db
