FROM python:3.9-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/app

COPY ./reqs/main.txt .
COPY ./reqs/tests.txt .

RUN apk add --no-cache pandoc && \
    pip install --no-cache-dir -r main.txt && \
    pip install --no-cache-dir -r tests.txt