"""init

Revision ID: 52fe03c3fcb6
Revises: 
Create Date: 2023-03-15 02:00:13.205479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52fe03c3fcb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=7), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_metadata_hash'), 'users_metadata', ['hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_metadata_hash'), table_name='users_metadata')
    op.drop_table('users_metadata')
    # ### end Alembic commands ###
