"""

Revision ID: 988e649c3a5d
Revises: dd38093adbeb
Create Date: 2024-05-11 20:06:01.513421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988e649c3a5d'
down_revision = 'dd38093adbeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
